const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'public'),port=process.env.PORT||4173;
const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9+#. ]/g,' ');
const words=s=>[...new Set(norm(s).split(/\s+/).filter(x=>x.length>2))];
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(data))};
const skills=['javascript','typescript','python','java','react','node','node.js','sql','aws','azure','gcp','docker','kubernetes','machine learning','data analysis','excel','power bi','tableau','django','flask','html','css','git'];
function profile(resume,p={}){return {skills:skills.filter(x=>norm(resume).includes(norm(x))),terms:words(resume),titles:p.titles||'',location:p.location||'',remote:!!p.remote}}
function salary(s=''){return (s.match(/(?:\$|USD\s?)\s?\d{2,3}(?:,\d{3})?(?:\s?(?:-|–|to)\s?(?:\$|USD\s?)?\d{2,3}(?:,\d{3})?)?(?:\s?(?:\/|per )?(?:year|yr|hour))?/i)||[])[0]||'Not listed'}
async function feed(url){let r=await fetch(url,{headers:{'user-agent':'JobSeekerAgent/0.1'}});if(!r.ok)throw Error(`Source returned ${r.status}`);return r.json()}
async function jobs(query){let out=[],warnings=[];let a=await Promise.allSettled([feed(`https://remotive.com/api/remote-jobs?search=${encodeURIComponent(query)}`),feed('https://www.arbeitnow.com/api/job-board-api')]);
 if(a[0].status==='fulfilled')out.push(...(a[0].value.jobs||[]).map(x=>({company:x.company_name,title:x.title,location:x.candidate_required_location||'Remote',salary:x.salary||salary(x.description),url:x.url,source:'Remotive',description:x.description||'',posted:x.publication_date})));
 else warnings.push('Remotive unavailable');
 let terms=words(query);if(a[1].status==='fulfilled')out.push(...(a[1].value.data||[]).filter(x=>!terms.length||terms.some(t=>norm(`${x.title} ${x.description}`).includes(t))).slice(0,100).map(x=>({company:x.company_name,title:x.title,location:x.location||(x.remote?'Remote':'Not listed'),salary:salary(x.description),url:x.url,source:'Arbeitnow',description:x.description||'',posted:x.created_at})));
 else warnings.push('Arbeitnow unavailable');return {out,warnings}}
function rank(job,p){let text=norm(`${job.title} ${job.description} ${job.location}`),matched=p.skills.filter(x=>text.includes(norm(x))),titles=words(p.titles).filter(x=>norm(job.title).includes(x)),score=Math.min(55,matched.length*14)+Math.min(25,titles.length*10)+Math.min(20,p.terms.filter(x=>text.includes(x)).length)+(p.remote&&/remote/i.test(job.location)?8:0)+(p.location&&norm(job.location).includes(norm(p.location))?8:0);return {...job,fit:Math.min(100,score),matched,reason:matched.length?`Matches ${matched.join(', ')}${titles.length?'; target title aligns.':'.'}`:'Keyword-level match; review the listed requirements.'}}
function body(req){return new Promise((ok,bad)=>{let s='';req.on('data',x=>{s+=x;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(JSON.parse(s||'{}'))}catch{bad(Error('Invalid request'))}});req.on('error',bad)})}
http.createServer(async(req,res)=>{if(req.method==='POST'&&req.url==='/api/search'){try{let x=await body(req);if(!String(x.resume||'').trim())return json(res,400,{error:'Paste a resume first.'});let p=profile(x.resume,x.preferences),q=p.titles||p.skills.slice(0,3).join(' ')||'software engineer',{out,warnings}=await jobs(q),seen=new Set(),list=out.filter(j=>{let k=norm(`${j.company}|${j.title}|${j.location}`);if(seen.has(k))return false;seen.add(k);return !p.remote||/remote/i.test(j.location)}).map(j=>rank(j,p)).sort((a,b)=>b.fit-a.fit).slice(0,100);return json(res,200,{profile:p,query:q,total:list.length,jobs:list,warnings})}catch(e){return json(res,502,{error:e.message})}}
 let name=req.url==='/'?'index.html':req.url.slice(1),file=path.resolve(root,name);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end('Not found')}let types={'.html':'text/html','.js':'text/javascript','.css':'text/css'};res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file))}).listen(port,()=>console.log(`Open http://localhost:${port}`));
module.exports={profile,rank,salary};
